apiVersion: apps.grafana.com/v1alpha1
kind: AppManifest
metadata:
    name: alerting
spec:
    appName: alerting
    group: rules.alerting.grafana.app
    kinds:
        - kind: AlertRule
          scope: Namespaced
          versions:
            - name: v0alpha1
              schema:
                spec:
                    properties:
                        annotations:
                            additionalProperties:
                                type: string
                            type: object
                        dashboardUID:
                            type: string
                        data:
                            additionalProperties:
                                properties:
                                    datasourceUID:
                                        pattern: ^[a-zA-Z0-9_]+$
                                        type: string
                                    model: {}
                                    queryType:
                                        type: string
                                    relativeTimeRange:
                                        properties:
                                            from:
                                                pattern: ^((([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?|0)$
                                                type: string
                                            to:
                                                pattern: ^((([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?|0)$
                                                type: string
                                        required:
                                            - from
                                            - to
                                        type: object
                                    source:
                                        type: boolean
                                required:
                                    - queryType
                                    - relativeTimeRange
                                    - datasourceUID
                                    - model
                                type: object
                            type: object
                        execErrState:
                            default: Error
                            enum:
                                - Error
                                - Ok
                                - Alerting
                                - KeepLast
                            type: string
                        for:
                            pattern: ^((([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?|0)$
                            type: string
                        interval:
                            pattern: ^((([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?|0)$
                            type: string
                        keepFiringFor:
                            pattern: ^((([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?|0)$
                            type: string
                        labels:
                            additionalProperties:
                                type: string
                            type: object
                        missingSeriesEvalsToResolve:
                            type: integer
                        noDataState:
                            default: NoData
                            enum:
                                - NoData
                                - Ok
                                - Alerting
                                - KeepLast
                            type: string
                        notificationSettings:
                            items:
                                properties:
                                    activeTimeIntervals:
                                        items:
                                            type: string
                                        type: array
                                    groupBy:
                                        items:
                                            type: string
                                        type: array
                                    groupInterval:
                                        type: string
                                    groupWait:
                                        type: string
                                    muteTimeIntervals:
                                        items:
                                            type: string
                                        type: array
                                    receiver:
                                        type: string
                                    repeatInterval:
                                        type: string
                                required:
                                    - receiver
                                type: object
                            type: array
                        panelID:
                            type: integer
                        paused:
                            type: boolean
                        title:
                            type: string
                    required:
                        - title
                        - data
                        - interval
                        - noDataState
                        - execErrState
                        - for
                        - keepFiringFor
                        - annotations
                        - labels
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                status:
                    properties:
                        additionalFields:
                            description: additionalFields is reserved for future use
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                        operatorStates:
                            additionalProperties:
                                properties:
                                    descriptiveState:
                                        description: descriptiveState is an optional more descriptive state field which has no requirements on format
                                        type: string
                                    details:
                                        description: details contains any extra information that is operator-specific
                                        type: object
                                        x-kubernetes-preserve-unknown-fields: true
                                    lastEvaluation:
                                        description: lastEvaluation is the ResourceVersion last evaluated
                                        type: string
                                    state:
                                        description: |-
                                            state describes the state of the lastEvaluation.
                                            It is limited to three possible states for machine evaluation.
                                        enum:
                                            - success
                                            - in_progress
                                            - failed
                                        type: string
                                required:
                                    - lastEvaluation
                                    - state
                                type: object
                            description: |-
                                operatorStates is a map of operator ID to operator state evaluations.
                                Any operator which consumes this kind SHOULD add its state evaluation information to this field.
                            type: object
                    type: object
              selectableFields:
                - spec.title
          conversion: false
        - kind: RecordingRule
          scope: Namespaced
          versions:
            - name: v0alpha1
              schema:
                spec:
                    properties:
                        data:
                            additionalProperties:
                                properties:
                                    datasourceUID:
                                        pattern: ^[a-zA-Z0-9_]+$
                                        type: string
                                    model: {}
                                    queryType:
                                        type: string
                                    relativeTimeRange:
                                        properties:
                                            from:
                                                pattern: ^((([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?|0)$
                                                type: string
                                            to:
                                                pattern: ^((([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?|0)$
                                                type: string
                                        required:
                                            - from
                                            - to
                                        type: object
                                    source:
                                        type: boolean
                                required:
                                    - queryType
                                    - relativeTimeRange
                                    - datasourceUID
                                    - model
                                type: object
                            type: object
                        interval:
                            pattern: ^((([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?|0)$
                            type: string
                        labels:
                            additionalProperties:
                                type: string
                            type: object
                        metric:
                            pattern: ^[a-zA-Z_:][a-zA-Z0-9_:]*$
                            type: string
                        paused:
                            type: boolean
                        targetDatasourceUID:
                            pattern: ^[a-zA-Z0-9_]+$
                            type: string
                        title:
                            type: string
                    required:
                        - title
                        - data
                        - interval
                        - metric
                        - labels
                        - targetDatasourceUID
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                status:
                    properties:
                        additionalFields:
                            description: additionalFields is reserved for future use
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                        operatorStates:
                            additionalProperties:
                                properties:
                                    descriptiveState:
                                        description: descriptiveState is an optional more descriptive state field which has no requirements on format
                                        type: string
                                    details:
                                        description: details contains any extra information that is operator-specific
                                        type: object
                                        x-kubernetes-preserve-unknown-fields: true
                                    lastEvaluation:
                                        description: lastEvaluation is the ResourceVersion last evaluated
                                        type: string
                                    state:
                                        description: |-
                                            state describes the state of the lastEvaluation.
                                            It is limited to three possible states for machine evaluation.
                                        enum:
                                            - success
                                            - in_progress
                                            - failed
                                        type: string
                                required:
                                    - lastEvaluation
                                    - state
                                type: object
                            description: |-
                                operatorStates is a map of operator ID to operator state evaluations.
                                Any operator which consumes this kind SHOULD add its state evaluation information to this field.
                            type: object
                    type: object
              selectableFields:
                - spec.title
          conversion: false
