apiVersion: 1

prune: true

datasources:
  - name: TestData
    type: testdata

  - name: Prometheus metrics
    uid: fs-prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true

  - name: Loki logs
    uid: fs-loki
    type: loki
    url: http://loki:3100

  - name: Tempo traces
    uid: fs-tempo
    type: tempo
    url: http://tempo:3200
